### PR TITLE
Add rheumatoid man

### PR DESCRIPTION
**Pull request by BlaineVlan**
The previous Rheumatoid man did not have enough joints to comply with international standards and Rheumatology joint counts. 

Added C-spine, T-Spine, L-Spine, Sacroiliac joints, Talonavicular and Tarsometatarsal joints. Remapped the new image, and updated the config file accordingly.

### CODE REVIEW

**Comment by marlycormar** [comment]
Hi Blaine,

Thank you for improving your PR. Please address the issues below.

- In the newly added regions on the mapping file `rheumatoid_man_map.html` (from f69-f79) there were invalid characters: “ as opposed to ". This difference is subtle but causes the new regions to not display. A good general approach to avoid these issues is to use a text editor such as [Sublime](https://www.sublimetext.com).
- Regions f47 and f48 were redefined. Please remove those lines in the mapping file (lines 48-49).

**Comment by BlaineVlan** [comment]
Hi Marly,

Thanks for reviewing the update.

I had done some work on the map at home on a Mac, which I had not realized had changed the quotation marks. I have hopefully removed them all.

I also realized that my new image had been resized by a pixel after I edited in the extra joints. I am not sure how much of a difference this would have made to the map, but I remapped most of the joints to accommodate the change just in case.

Thanks for pointing out the duplicate ankle area. I have removed the ankle, and adjusted the area codes accordingly.

**Comment by marlycormar** [comment]
Can you fix the `Left Acromioclavicular` circle? It is incorrectly located.

**Comment by BlaineVlan** [comment]
Hi Marly,

Didn't see I had left a digit out. It is now fixed.

Thanks for reviewing.

**Pull request merged**
