### PR TITLE
Adds PI-RADS v2.1 imagemap

### PR DESCRIPTION
**Pull request by GeeEssEff**
Adds v2.1 (2019) PI-RADS in response to issue #36. Does not replace original PIRADS maps nor images, adds as a new imagemap.

### CODE REVIEW

**Comment by marlycormar** [comment]
Hi @frgeof, were you able to make this PR on the REDCap module repo, namely, (https://github.com/ctsit/imagemap)?

**Comment by GeeEssEff** [comment]
🤦 I thought we had completed that in December.

**Comment by marlycormar** [comment]
It seems your code is already included in the main imagemap repo, develop branch:

https://github.com/ctsit/imagemap/tree/develop

If you would like to make further changes, you can submit a PR in https://github.com/ctsit/imagemap.

**Comment by GeeEssEff** [comment]
Ah-ha! No wonder I was completely confused. 😀

**Pull request merged**
